### ISSUE TITLE
TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by kpeters-cbsi** [rayepps/radash#125]
When I try to run the following script, I get `TypeError: Cannot read properties of undefined (reading 'try')`:

```
import _ from 'radash';

async function main() {
  console.debug('radash', { radash: _ });

  const [err, res] = await _.try(() => {
    throw new Error('O NOES');
  })();
}

main().then()
```

Full output:
```
$ npx ts-node packages/nebula-api/sketches/radash.ts

radash { radash: undefined }
/Users/cpete0624/work/ops-nebula/packages/nebula-api/sketches/radash.ts:8
  const [err, res] = await _.try(() => {
                             ^
TypeError: Cannot read properties of undefined (reading 'try')
    at main (/Users/cpete0624/work/ops-nebula/packages/nebula-api/sketches/radash.ts:8:30)
    at Object.<anonymous> (/Users/cpete0624/work/ops-nebula/packages/nebula-api/sketches/radash.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/Users/cpete0624/work/ops-nebula/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/cpete0624/work/ops-nebula/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/Users/cpete0624/work/ops-nebula/node_modules/ts-node/src/bin.ts:649:14)
```

Using Typescript 4.8.4, radash 8.0.3

**Comment by kpeters-cbsi** [comment]
Interestingly, if I replace `import _ from 'radash'` with `import * as _ from 'radash'`, it works. So I would imagine it's something in my Typescript config, but I'm not sure what.

**Comment by rayepps** [comment]
Ah yes, I think it was version `6` when radash removed the default export. It was just me using it back then, maybe it was a mistake to remove. Now that its tree-shakeable it's probably ok.

Did you see `import _ from 'radash'` somewhere, maybe in the docs? I'd like to make sure I get it updated so others don't hit this.
